# Generated by Django 5.0.6 on 2024-06-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationEtagereProduit',
            fields=[
                ('id_association_etagere_produit', models.SmallAutoField(primary_key=True, serialize=False)),
                ('id_etagere', models.SmallIntegerField(blank=True, null=True)),
                ('id_produit', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'association_etagere_produit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AssociationRayonEtagere',
            fields=[
                ('id_association_rayon_etagere', models.SmallAutoField(primary_key=True, serialize=False)),
                ('id_rayon', models.SmallIntegerField(blank=True, null=True)),
                ('id_etagere', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'association_rayon_etagere',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id_categorie_produit', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nom_categorie_produit', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'categorie_produit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Etagere',
            fields=[
                ('id_etagere', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nom_etagere', models.CharField(blank=True, max_length=10, null=True)),
                ('id_rayon', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'etagere',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(blank=True, max_length=30, null=True)),
                ('id_categorie_produit', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'produit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('id_rayon', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nom_rayon', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'rayon',
                'managed': True,
            },
        ),
    ]
