# Generated by Django 5.0.6 on 2024-06-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0003_alter_produit_categorie_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='categorie_produit',
        ),
        migrations.AddField(
            model_name='produit',
            name='id_categorie_produit',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
