# Generated by Django 5.0.6 on 2024-06-23 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0007_remove_produit_id_categorie_produit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie_produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magasin.categorieproduit'),
        ),
    ]
