# Generated by Django 5.0.6 on 2024-06-23 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0009_remove_produit_categorie_produit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='id_categorie_produit',
            field=models.ForeignKey(blank=True, db_column='id_categorie_produit', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='magasin.categorieproduit'),
        ),
    ]
