# Generated by Django 5.0.6 on 2024-06-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0010_alter_produit_id_categorie_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='id_categorie_produit',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
