# Generated by Django 5.0.6 on 2024-07-13 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0011_alter_produit_id_categorie_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeCourses',
            fields=[
                ('id_liste_courses', models.AutoField(primary_key=True, serialize=False)),
                ('nom_liste', models.CharField(max_length=100)),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'liste_courses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ElementListe',
            fields=[
                ('id_element_liste', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasin.produit')),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='magasin.listecourses')),
            ],
            options={
                'db_table': 'element_liste',
                'managed': True,
            },
        ),
    ]
