# Generated by Django 5.0.6 on 2024-07-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0012_listecourses_elementliste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementliste',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
    ]
