# Generated by Django 5.0.6 on 2024-09-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0013_alter_elementliste_quantite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementliste',
            options={},
        ),
        migrations.AlterModelTable(
            name='elementliste',
            table=None,
        ),
    ]
