# Generated by Django 5.0.6 on 2024-09-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0014_alter_elementliste_options_alter_elementliste_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementliste',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='elementliste',
            table='element_liste',
        ),
    ]
